name: Build

on: workflow_dispatch

jobs:
  build:

    name: Generate apk
    runs-on: ubuntu-latest
    
    steps:        
        uses: actions/checkout@v2
        
        name: Build the app
        run: ./gradlew assembleDebug
        
        name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: app/build/outputs/apk/debug/
